name: Mirroring

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:EpitechPromo2025/B-CCP-400-NAN-4-1-theplazza-alexandre.tomasin.git
          ssh_private_key:
            ${{ secrets.KEY_SSH }}